# 1. 넘파이

## 1~10

In [53]:
import numpy as np

In [54]:
data = [1, 2, 3]

In [55]:
np.array(data)

array([1, 2, 3])

In [56]:
data =[]
for i in range(100) :
    data.append(i)
np.array(data)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [57]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [58]:
data=[]
for i in range(1, 10) :
    k = 3 * i
    data.append(k)
np.array(data)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [59]:
arr= np.arange(1,10) * 3

In [60]:
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [61]:
np.arange(2,1000,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208,
       210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234,
       236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260,
       262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286,
       288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312,
       314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338,
       340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 36

In [62]:
np.arange(0.0,1.0,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [63]:
data = [0, 1, 2, 3, 4, 5]

In [64]:
np.asarray(data)

array([0, 1, 2, 3, 4, 5])

In [65]:
np.asarray(data).reshape(2,-1)

array([[0, 1, 2],
       [3, 4, 5]])

In [66]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])

In [67]:
arr.reshape(6)

array([0, 1, 2, 3, 4, 5])

In [68]:
arr = np.arange(3)

In [69]:
arr

array([0, 1, 2])

In [70]:
arr.reshape(3,1)

array([[0],
       [1],
       [2]])

## 11~20

In [73]:
np.arange(6).reshape(2,-1)

array([[0, 1, 2],
       [3, 4, 5]])

In [76]:
np.arange(1,0)

array([], dtype=int32)

In [81]:
np.ones(20, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [84]:
data = [1] *20

In [85]:
data

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [87]:
np.array(data)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [89]:
np.ones(20, dtype=int).reshape(4,-1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [90]:
arr=np.ones(100, dtype=int).reshape(10,-1)

In [91]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [92]:
arr *255

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

In [93]:
np.zeros(12).reshape(3,-1)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [98]:
np.ones((10,10)) *255

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])

In [100]:
data=[1, 2, 3]

In [101]:
data

[1, 2, 3]

In [103]:
np.array(data, dtype=np.int32)

array([1, 2, 3])

In [104]:
arr = np.array([1, 2, 3])

In [105]:
type(arr)

numpy.ndarray

In [106]:
type(arr.dtype)

numpy.dtype[int32]

In [107]:
arr.dtype

dtype('int32')

In [108]:
arr = np.array(['1', '2', '3'])

In [109]:
type(arr)

numpy.ndarray

In [113]:
type(arr.dtype)

numpy.dtype[str_]

In [114]:
print(arr.dtype)

<U1


In [115]:
arr = np.array([1, 2, 3])

In [116]:
print(arr.dtype)

int32


In [119]:
arr.astype(np.int16)

array([1, 2, 3], dtype=int16)

## 21~30

In [120]:
arr = np.array([1.1, 2.1, 3.1])
arr

array([1.1, 2.1, 3.1])

In [124]:
arr.astype(np.int32)

array([1, 2, 3])

In [125]:
np.linspace(0,10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [130]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [137]:
arr[2]

array([6, 7, 8])

In [138]:
arr[-1]

array([6, 7, 8])

In [144]:
arr[0,1]

1

In [142]:
arr[1][1]

4

In [143]:
arr[0:2][1]

array([3, 4, 5])

In [146]:
arr[0:3,1]

array([1, 4, 7])

In [147]:
arr[:,1]

array([1, 4, 7])

In [149]:
arr = np.arange(25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [151]:
arr[3,2]

17

In [152]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [162]:
arr[1::2]

array([1, 3])

In [163]:
arr[[1,3]]

array([1, 3])

In [164]:
arr[1]

1

In [165]:
arr[2]

2

In [166]:
arr[3]

3

In [167]:
arr[0]

0

In [169]:
arr[[1,3]]

array([1, 3])

In [170]:
arr = np.arange(25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [171]:
arr[0]

array([0, 1, 2, 3, 4])

In [172]:
arr[1][1]

6

In [173]:
arr[1][1:]

array([6, 7, 8, 9])

In [174]:
arr[1,1:]

array([6, 7, 8, 9])

In [175]:
arr[:,1]

array([ 1,  6, 11, 16, 21])

In [176]:
arr[:,0]

array([ 0,  5, 10, 15, 20])

In [177]:
arr[:,:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [178]:
arr[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [186]:
arr[0,-1]

4

In [187]:
arr[0, 3]

3

In [202]:
arr = np.arange(25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [203]:
arr[ [0,-1] , [0, 3] ]

array([ 0, 23])

## 31~40

In [ ]:
data = [1, 2, 3]

In [205]:
arr =np.array(data)

In [206]:
arr *10

array([10, 20, 30])

In [207]:
ndarray=np.array(data)**2

In [208]:
ndarray

array([1, 4, 9], dtype=int32)

In [209]:
np.array(data) **(0.5)

array([1.        , 1.41421356, 1.73205081])

In [210]:
np.sqrt(data)

array([1.        , 1.41421356, 1.73205081])

In [211]:
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])

In [216]:
score.mean(axis=0)

array([12., 18.])

In [217]:
score.std(axis=1)

array([5., 1.])

In [218]:
a = np.arange(   4).reshape(2,2)
b = np.arange(1, 5).reshape(2,2)

In [219]:
a+b

array([[1, 3],
       [5, 7]])

In [220]:
a*b

array([[ 0,  2],
       [ 6, 12]])

In [221]:
arr = np.arange(9).reshape(3, 3)

In [222]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [223]:
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [224]:
arr.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [242]:
arr = np.arange(10)

In [243]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [251]:
arr[0:10:2]

array([0, 2, 4, 6, 8])

In [252]:
arr[1:10:2]

array([1, 3, 5, 7, 9])

In [255]:
arr[4:7]

array([4, 5, 6])

In [256]:
arr[(arr>3)&(arr<7)]

array([4, 5, 6])

## 41-50

In [257]:
arr = np.array([-1, 2, -3, 4])

In [259]:
arr[(arr<0)] =0

In [260]:
arr

array([0, 2, 0, 4])

In [268]:
arr = np.array([-1, 2, -3, 4])

In [262]:
arr.dtype

dtype('int32')

In [264]:
cond=arr<0

In [266]:
arr[cond] = -arr[cond]

In [267]:
arr

array([1, 2, 3, 4])

In [269]:
arr

array([-1,  2, -3,  4])

In [270]:
abs(arr)

array([1, 2, 3, 4])

In [271]:
arr = np.array([-1, 2, -3, 4])

In [272]:
np.where(arr >=0, arr+10, arr-10)

array([-11,  12, -13,  14])

In [273]:
arr = [1, 2, 3, 4, 5]

In [283]:
np.random.shuffle(arr)

In [276]:
arr

[3, 1, 5, 2, 4]

In [277]:
arr = np.array([1, 2, 3, 4, 5])

In [284]:
arr.argmin()

3

In [285]:
arr.argmax()

1

In [286]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [304]:
np.sort(arr)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [306]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

In [308]:
arrr =np.vstack((arr1,arr2))

In [309]:
arrr

array([[1, 2],
       [3, 4]])

In [310]:
arr = np.array([ [1, 2], [3, 4] ])

In [317]:
arr.reshape(-1)

array([1, 2, 3, 4])

# 2. 시리즈 생성

## 51~60

In [319]:
import pandas as pd

In [320]:
data = [100,200,300]
s= pd.Series(data)

In [322]:
s.index = ['철수','영희','아름']

In [323]:
s

철수    100
영희    200
아름    300
dtype: int64

In [325]:
s.loc['철수'] =500

In [326]:
s

철수    500
영희    200
아름    300
dtype: int64

In [327]:
s

철수    500
영희    200
아름    300
dtype: int64

In [328]:
dict_ = {'철수':100, '영희':200, '아름':300}

In [329]:
score = pd.Series(dict_)

In [330]:
score

철수    100
영희    200
아름    300
dtype: int64

In [332]:
fin={'삼성전자':	73000,
'셀트리온':	356000,
'카카오'	:367000,
'삼성전자우':	68600,
'현대바이오':	34150}

In [333]:
fin

{'삼성전자': 73000, '셀트리온': 356000, '카카오': 367000, '삼성전자우': 68600, '현대바이오': 34150}

In [347]:
fin_s=pd.Series(fin)

In [348]:
fin

{'삼성전자': 73000, '셀트리온': 356000, '카카오': 367000, '삼성전자우': 68600, '현대바이오': 34150}

In [349]:
fin_s

삼성전자      73000
셀트리온     356000
카카오      367000
삼성전자우     68600
현대바이오     34150
dtype: int64

In [350]:
fin_s.columns =['종목명','종가']

In [351]:
fin_s.index

Index(['삼성전자', '셀트리온', '카카오', '삼성전자우', '현대바이오'], dtype='object')

In [352]:
fin_s.values

array([ 73000, 356000, 367000,  68600,  34150], dtype=int64)

In [355]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = pd.Series(data, index)

In [356]:
s

철수    100
영희    200
아름    300
dtype: int64

In [357]:
s.to_dict()

{'철수': 100, '영희': 200, '아름': 300}