# 3. 시리즈데이터 타입

## 61~70

In [4]:
import pandas as pd
import numpy as np

In [4]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = pd.Series(data, index)

In [5]:
s

철수    100
영희    200
아름    300
dtype: int64

In [6]:
type(s)

pandas.core.series.Series

In [9]:
s.dtypes

dtype('int64')

In [11]:
s.dtype

dtype('int64')

In [13]:
data = [  10,  "가" ]
s = pd.Series( data )

In [14]:
s

0    10
1     가
dtype: object

In [17]:
s.dtypes

dtype('O')

In [18]:
type(s)

pandas.core.series.Series

In [19]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = pd.Series(data, index)

In [20]:
s

철수    100
영희    200
아름    300
dtype: int64

In [22]:
print(s.index.dtype)

object


In [37]:
data = {
    "2020-12-11": 73400,
    "2020-12-10": 72900,
    "2020-12-09": 73900,
    "2020-12-08": 71700,
    "2020-12-07": 72900
}

In [33]:
s = pd.Series(data)
s.name = "종가"
s.index.name = "날짜"

In [34]:
s

날짜
2020-12-11    73400
2020-12-10    72900
2020-12-09    73900
2020-12-08    71700
2020-12-07    72900
Name: 종가, dtype: int64

In [25]:
s

날짜
2020-12-11    73400
2020-12-10    72900
2020-12-09    73900
2020-12-08    71700
2020-12-07    72900
Name: 종가, dtype: int64

In [47]:
data = {"apple": 1500, "banana": 3000}
s = pd.Series(data)

In [48]:
data

{'apple': 1500, 'banana': 3000}

In [49]:
s

apple     1500
banana    3000
dtype: int64

In [52]:
s.to_dict()

{'apple': 1500, 'banana': 3000}

In [53]:
s

apple     1500
banana    3000
dtype: int64

In [54]:
data = {"apple": 1500, "banana": 3000}
s = pd.Series(data)
s

apple     1500
banana    3000
dtype: int64

In [57]:
s.index.name='icecream'

In [58]:
s

icecream
apple     1500
banana    3000
dtype: int64

In [59]:
s = pd.Series(data=[1, 2, 3])

In [60]:
s.name='number'

In [61]:
s

0    1
1    2
2    3
Name: number, dtype: int64

In [62]:
s[2]

3

In [63]:
s[2] = None

In [64]:
s

0    1.0
1    2.0
2    NaN
Name: number, dtype: float64

In [65]:
s.index.dtype

dtype('int64')

In [66]:
s.index.to_numpy()

array([0, 1, 2], dtype=int64)

In [67]:
s = pd.Series([1, 2, 3])

In [68]:
s.dtype

dtype('int64')

In [69]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]}, index=['a', 'b', 'c']); 

In [70]:
df

A  B
a  1  4
b  2  5
c  3  6

In [72]:
array = np.array(df.index.array)
print(array)

['a' 'b' 'c']


In [73]:
array.dtype

dtype('O')

# 4. 시리즈 인덱싱과 슬라이싱

## 71~80

In [1]:
import pandas as pd

s = pd.Series([1, 2, 'python'])
print(s.dtype)

object


In [2]:
s = pd.Series(['1', '2', '3'])

In [3]:
s

0    1
1    2
2    3
dtype: object

In [5]:
s.astype('int32')

0    1
1    2
2    3
dtype: int32

In [12]:
amount =pd.Series(['50000','1','4000'], index= ['BTC','XRP','ETH'])

In [18]:
amount=amount.astype('float')

In [19]:
amount

BTC    50000.0
XRP        1.0
ETH     4000.0
dtype: float64

In [21]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = pd.Series(data, index)

In [22]:
s

철수    100
영희    200
아름    300
dtype: int64

In [23]:
s['영희']

200

In [24]:
s.iloc[1]

200

In [25]:
s.loc['영희']

200

In [30]:
print(s["영희"])

200


In [32]:
s.iloc[:2]

철수    100
영희    200
dtype: int64

In [33]:
data = [100, 200, 300, 400, 500, 600]
index = ["08/01", "08/02", "08/03", "08/04", "08/05", "08/06"]
s = pd.Series(data, index)

In [34]:
s

08/01    100
08/02    200
08/03    300
08/04    400
08/05    500
08/06    600
dtype: int64

In [41]:
s.iloc[:3].index

Index(['08/01', '08/02', '08/03'], dtype='object')

In [40]:
s.iloc[::2].values

array([100, 300, 500], dtype=int64)

# 5. 시리즈 수정, 추가 및 삭제

## 81~90

In [52]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = pd.Series(data, index)

In [43]:
s

철수    100
영희    200
아름    300
dtype: int64

In [53]:
s.loc["순이"]=400

In [45]:
s

철수    100
영희    200
아름    300
순이    400
dtype: int64

In [48]:
s.drop("철수", inplace=True)

In [54]:
s

철수    100
영희    200
아름    300
순이    400
dtype: int64

In [55]:
s=s.iloc[1:]

In [56]:
s

영희    200
아름    300
순이    400
dtype: int64

In [57]:
from pandas import Series

data = {
    "삼성전자": "전기,전자",
    "LG전자": "전기,전자",
    "현대차": "운수장비",
    "NAVER": "서비스업",
    "카카오": "서비스업"
}
s = Series(data)

In [58]:
s

삼성전자     전기,전자
LG전자     전기,전자
현대차       운수장비
NAVER     서비스업
카카오       서비스업
dtype: object

In [59]:
s.unique()

array(['전기,전자', '운수장비', '서비스업'], dtype=object)

In [60]:
s = pd.Series(
    data = [9000, 9000, 8000, 9000, 10000],
    index = ['김과장', '이대리', '박전무', '이대리', '이대리']
)

In [63]:
s.unique()

array([ 9000,  8000, 10000], dtype=int64)

In [68]:
s.index.unique()

Index(['김과장', '이대리', '박전무'], dtype='object')

In [69]:
s.value_counts()

9000     3
8000     1
10000    1
dtype: int64

In [72]:
s.index.value_counts()

이대리    3
김과장    1
박전무    1
dtype: int64

In [74]:
data = {
    "삼성전자": "전기,전자",
    "LG전자": "전기,전자",
    "현대차": "운수장비",
    "NAVER": "서비스업",
    "카카오": "서비스업"
}
s = Series(data)

In [75]:
s.value_counts()

전기,전자    2
서비스업     2
운수장비     1
dtype: int64

In [76]:
data = {"매출액" : "300", "PER" : None, "PBR" : "2.0"}

In [77]:
data

{'매출액': '300', 'PER': None, 'PBR': '2.0'}

In [80]:
s=pd.Series(data)

In [86]:
s=s.reset_index()

In [87]:
s

index     0
0   매출액   300
1   PER  None
2   PBR   2.0

In [94]:
s.columns = [ '항목','값']

In [96]:
s

항목     값
0  매출액   300
1  PER  None
2  PBR   2.0

# 6. 시리즈 정렬, 순위 및 비교

## 91~100

In [97]:
data = [100, 300, 200]
index = ["08/01", "08/02", "08/03"]
s = Series(data, index)

In [98]:
s

08/01    100
08/02    300
08/03    200
dtype: int64

In [99]:
s.sort_values()

08/01    100
08/03    200
08/02    300
dtype: int64

In [100]:
s.iloc[[0,2,1]]

08/01    100
08/03    200
08/02    300
dtype: int64

In [101]:
s.loc[['08/01','08/03','08/02']]

08/01    100
08/03    200
08/02    300
dtype: int64

In [3]:
import numpy as np

data = np.random.randint(10, size=4)
s = Series(data)

NameError: name 'Series' is not defined

In [103]:
s

0    5
1    6
2    2
3    6
dtype: int32

In [104]:
s.sort_values()

2    2
0    5
1    6
3    6
dtype: int32

In [108]:
s.sort_values(ascending=False)

1    6
3    6
0    5
2    2
dtype: int32

In [109]:
s = Series(np.random.randint(10, size=4), ["b", "c", "a", "d"])

In [110]:
s

b    4
c    6
a    5
d    8
dtype: int32

In [111]:
s.sort_index()

a    5
b    4
c    6
d    8
dtype: int32

In [112]:
data = [100, 300, 200]
s = Series(data)

In [113]:
s

0    100
1    300
2    200
dtype: int64

In [115]:
s**4

0     100000000
1    8100000000
2    1600000000
dtype: int64

In [116]:
data = [100, 300, 200]
s0 = Series(data, ["a", "b", "c"])
s1 = Series(data, ["a", "c", "b"])

In [117]:
data

[100, 300, 200]

In [118]:
s0

a    100
b    300
c    200
dtype: int64

In [119]:
s1

a    100
c    300
b    200
dtype: int64

In [120]:
s0 + s1

a    200
b    500
c    500
dtype: int64

In [121]:
high = Series(data=[51500, 51200, 52500], index=["5/1", "5/2", "5/3"])
low = Series(data=[50700, 50500, 50500], index=["5/1", "5/2", "5/4"])

In [122]:
high

5/1    51500
5/2    51200
5/3    52500
dtype: int64

In [123]:
low

5/1    50700
5/2    50500
5/4    50500
dtype: int64

In [126]:
high - low

5/1    800.0
5/2    700.0
5/3      NaN
5/4      NaN
dtype: float64

In [7]:
import pandas as pd
import numpy as np

In [9]:
s =pd.Series(data=[51500, 51200, 52500], index=["5/1", "5/2", "5/3"])

In [10]:
s

5/1    51500
5/2    51200
5/3    52500
dtype: int64

In [11]:
s1=s < 52000

In [12]:
s1

5/1     True
5/2     True
5/3    False
dtype: bool

In [13]:
s[s1]

5/1    51500
5/2    51200
dtype: int64

In [14]:
조건 = s.index > "5/1"

In [15]:
s.loc[조건]

5/2    51200
5/3    52500
dtype: int64

In [16]:
s

5/1    51500
5/2    51200
5/3    52500
dtype: int64

In [28]:
s = pd.Series(data=[51500, 51200, 52500], index=["5/1", "5/2", "5/3"])

In [30]:
s

5/1    51500
5/2    51200
5/3    52500
dtype: int64

In [29]:
조건0 = s >= 51400
조건1 = s <= 53000
(조건0 & 조건1).index

Index(['5/1', '5/2', '5/3'], dtype='object')

In [31]:
조건=s<= 52000

In [32]:
len(s[조건])

2

# 7. 시리즈 기본 메소드

## 101~110

In [33]:
data = {'2020-12-07':'72900','2020-12-08':'71700','2020-12-09':'73900','2020-12-10':'72900','2020-12-11':'73400'}

In [34]:
jongga=pd.Series(data)

In [41]:
jongga=jongga.astype('int')

In [42]:
jongga.sum()

364800

In [44]:
jongga.mean()

72960.0

In [45]:
ratio={'2020-12-07':1,'2020-12-08':1.02,'2020-12-09':1.03,'2020-12-10':0.99,'2020-12-11':1.01}

In [52]:
ratio=pd.Series(data=ratio)

In [53]:
jongga=jongga.astype('float')

In [54]:
jongga * ratio

2020-12-07    72900.0
2020-12-08    73134.0
2020-12-09    76117.0
2020-12-10    72171.0
2020-12-11    74134.0
dtype: float64

In [55]:
ratio.product() #각 행의 value들을 곱한값

1.05049494

In [56]:
jongga

2020-12-07    72900.0
2020-12-08    71700.0
2020-12-09    73900.0
2020-12-10    72900.0
2020-12-11    73400.0
dtype: float64

In [57]:
jongga.max()

73900.0

In [58]:
jongga.min()

71700.0

# 8. 시리즈 데이터 변경

## 111~120

In [59]:
import numpy as np
from pandas import Series 

data = [1, 2, 3, 4, np.nan]
s = Series(data=data)

In [60]:
s

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
dtype: float64

In [61]:
s.count()

4

In [62]:
data = ["100", "200", "300"]
index = ["철수", "영희", "아름"]
s = Series(data, index)

In [67]:
s

철수    100
영희    200
아름    300
dtype: object

In [68]:
s.astype('int')

철수    100
영희    200
아름    300
dtype: int32

In [66]:
s.astype(np.int32)

철수    100
영희    200
아름    300
dtype: int32

In [69]:
data = ["100,000", "200,000", "300,000"]
index = ["철수", "영희", "아름"]
s = Series(data, index)

In [70]:
s

철수    100,000
영희    200,000
아름    300,000
dtype: object

In [71]:
s.str.replace(',', '').astype('int')

철수    100000
영희    200000
아름    300000
dtype: int32

In [72]:
s = pd.Series(["30세", "40세", "50세"], index=["김대리", "이과장", "박차장"])
print(s)
# 김대리    30세
# 이과장    40세
# 박차장    50세
# dtype: object

김대리    30세
이과장    40세
박차장    50세
dtype: object


In [73]:
s

김대리    30세
이과장    40세
박차장    50세
dtype: object

In [75]:
s.str.replace('세','').astype('int32')

김대리    30
이과장    40
박차장    50
dtype: int32

In [76]:
s = pd.Series([1, 2, 3, 4], index=["d", "c", "a", "b"])
s

d    1
c    2
a    3
b    4
dtype: int64

In [77]:
s.sort_index()

a    3
b    4
c    2
d    1
dtype: int64

In [78]:
s = pd.Series([1, 2, 3])

In [79]:
s

0    1
1    2
2    3
dtype: int64

In [80]:
list(s)

[1, 2, 3]

In [81]:
s = pd.Series([1, 2, 3])

In [82]:
dict(s)

{0: 1, 1: 2, 2: 3}

In [83]:
s = pd.Series([1, 2, 3, np.nan])

In [84]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [85]:
s.dropna(inplace=True)

In [86]:
s

0    1.0
1    2.0
2    3.0
dtype: float64

In [106]:
s = pd.Series(["1,234", "5,678", "9,876"])

In [100]:
s

0    1,234
1    5,678
2    9,876
dtype: object

In [107]:
s1 = pd.Series(['1234','5678','9876'])

In [102]:
s1

0    1234
1    5678
2    9876
dtype: object

In [103]:
s.map(s1)

0    NaN
1    NaN
2    NaN
dtype: object

In [116]:
s1

0    1234
1    5678
2    9876
dtype: object

In [105]:
s1.map(s)

0    NaN
1    NaN
2    NaN
dtype: object

In [119]:
s=s.str.replace(',','')

In [120]:
s

0    1234
1    5678
2    9876
dtype: object

In [121]:
s = pd.Series([10, 100, 1000])

In [122]:
s

0      10
1     100
2    1000
dtype: int64

In [123]:
s.apply(np.log10)

0    1.0
1    2.0
2    3.0
dtype: float64

# 9. 시리즈 기타 주제

## 121~130

In [124]:
import numpy as np
from pandas import Series

data = [1, 2, 3, 4, np.nan]
s = Series(data=data)
s

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
dtype: float64

In [125]:
s.dropna()

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64

In [126]:
from pandas import Series

data = range(1, 11)
s = Series(data=data)
s

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [127]:
s.nlargest(n=3)

9    10
8     9
7     8
dtype: int64

In [128]:
s.nsmallest(n=3)

0    1
1    2
2    3
dtype: int64

In [129]:
import pandas as pd
from datetime import datetime
s = pd.Series([datetime(2020,1,1), datetime(2021,1,1), datetime(2022,1,1)])

In [130]:
s

0   2020-01-01
1   2021-01-01
2   2022-01-01
dtype: datetime64[ns]

In [140]:
s.dt.year

0    2020
1    2021
2    2022
dtype: int64

In [141]:
import pandas as pd
from datetime import datetime

index = [datetime(2020,1,1), datetime(2021,1,1), datetime(2022,1,1)]
data = [100, 200, 300]
s = pd.Series(data=data, index=index)

In [142]:
s

2020-01-01    100
2021-01-01    200
2022-01-01    300
dtype: int64

In [150]:
s.index.year

Int64Index([2020, 2021, 2022], dtype='int64')

In [151]:
type(s.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [152]:
import pandas as pd
from datetime import datetime
s = pd.Series([datetime(2022,1,1), datetime(2022,1,2), datetime(2022,1,3)])

In [153]:
s

0   2022-01-01
1   2022-01-02
2   2022-01-03
dtype: datetime64[ns]

In [154]:
s.dt.day

0    1
1    2
2    3
dtype: int64

In [157]:
import pandas as pd
from datetime import datetime

index = [datetime(2020,1,1), datetime(2021,1,1), datetime(2022,1,1)]
data = [100, 200, 300]
s = pd.Series(data=data, index=index)

In [158]:
s

2020-01-01    100
2021-01-01    200
2022-01-01    300
dtype: int64

In [159]:
s.index.strftime("%Y-%m-%d 00:00:00")

Index(['2020-01-01 00:00:00', '2021-01-01 00:00:00', '2022-01-01 00:00:00'], dtype='object')

In [160]:
s = pd.Series(["000020", "000040", "005930"])

In [161]:
s

0    000020
1    000040
2    005930
dtype: object

In [162]:
s.str.cat(sep=';')

'000020;000040;005930'

In [163]:
s = pd.Series(["000020", "000040", "005930"])

In [164]:
s

0    000020
1    000040
2    005930
dtype: object

In [165]:
'A' +s

0    A000020
1    A000040
2    A005930
dtype: object

In [166]:
s = pd.Series(["20", "40", "5930"])

In [167]:
s

0      20
1      40
2    5930
dtype: object

In [169]:
s.str.zfill(6)

0    000020
1    000040
2    005930
dtype: object