# 2.Logistic Classification

In [ ]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [ ]:
sonar = pd.read_csv('sonar_csv.csv')

In [ ]:
sonar

In [ ]:
sonar['Class'].value_counts()

In [ ]:
sonar['Class'].unique()

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
col_list= ['Class']
for col in col_list :
    label = LabelEncoder()
    label.fit(sonar[col].unique())
    sonar[col] = label.transform(sonar[col])

In [ ]:
sonar #1이 Rock 0이 Mine

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

In [ ]:
model = LogisticRegression()

In [ ]:
x = sonar.drop(['Class'],axis=1)

In [ ]:
y = sonar['Class']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1, random_state=0, stratify=y)

In [ ]:
model.fit(x_train, y_train)

In [ ]:
pre_train = model.predict(x_train)

In [ ]:
mean_absolute_error(pre_train, y_train)

In [ ]:
model.score(x_train, y_train)

In [ ]:
pre_test = model.predict(x_test)

In [ ]:
mean_absolute_error(pre_test, y_test)

In [ ]:
model.score(x_test, y_test)

------------------------

In [ ]:
model2 = LogisticRegression(max_iter=1000)

In [ ]:
model2.fit(x_train, y_train)

In [ ]:
model2.score(x_train, y_train)

In [ ]:
model2.score(x_test, y_test)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [ ]:
model.fit(x_train, y_train)

In [ ]:
model.score(x_train, y_train)

In [ ]:
model.score(x_test, y_test)

In [ ]:
model2.fit(x_train, y_train)

In [ ]:
model2.score(x_train, y_train)

In [ ]:
model2.score(x_test, y_test)

In [ ]:
sensor =x_train[0].reshape(1,-1)

In [ ]:
print(model2.predict(sensor) , ' 이 탐지되었습니다')

In [ ]:
model2.predict(sensor)

In [ ]:
pip search sklearn

In [ ]:
sonar.describe()

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
import pickle

In [ ]:
with open('scaler.pkl', 'wb') as f :
    pickle.dump(scaler, f)

In [ ]:
with open('model.pkl', 'wb') as f :
    pickle.dump(model, f)

In [ ]:
model = LogisticRegression()

In [ ]:
scaler = StandardScaler()

In [ ]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
model.fit(x_train, y_train)

In [ ]:
model.score(x_train, y_train)

In [ ]:
model.score(x_test, y_test)

In [ ]:
print(x_train.shape, y_train.shape)

In [ ]:
real = x.iloc[0].values.reshape(1, -1) #실제 데이터

In [ ]:
real

In [ ]:
real = scaler.transform(real)

In [ ]:
model.predict(real)[0]

In [ ]:
real[0]

----------------

In [1]:
import pandas as pd
import pickle

In [2]:
real_data = pd.read_csv('sonar_csv.csv')

In [3]:
real = real_data.drop('Class', axis=1)

In [5]:
real.iloc[100].values

array([0.0629, 0.1065, 0.1526, 0.1229, 0.1437, 0.119 , 0.0884, 0.0907,
       0.2107, 0.3597, 0.5466, 0.5205, 0.5127, 0.5395, 0.6558, 0.8705,
       0.9786, 0.9335, 0.7917, 0.7383, 0.6908, 0.385 , 0.0671, 0.0502,
       0.2717, 0.2839, 0.2234, 0.1911, 0.0408, 0.2531, 0.1979, 0.1891,
       0.2433, 0.1956, 0.2667, 0.134 , 0.1073, 0.2023, 0.1794, 0.0227,
       0.1313, 0.1775, 0.1549, 0.1626, 0.0708, 0.0129, 0.0795, 0.0762,
       0.0117, 0.0061, 0.0257, 0.0089, 0.0262, 0.0108, 0.0138, 0.0187,
       0.023 , 0.0057, 0.0113, 0.0131])

In [6]:
real2=real.iloc[100].values.reshape(1, -1) #reshape은 재구조화!!

In [7]:
real2

array([[0.0629, 0.1065, 0.1526, 0.1229, 0.1437, 0.119 , 0.0884, 0.0907,
        0.2107, 0.3597, 0.5466, 0.5205, 0.5127, 0.5395, 0.6558, 0.8705,
        0.9786, 0.9335, 0.7917, 0.7383, 0.6908, 0.385 , 0.0671, 0.0502,
        0.2717, 0.2839, 0.2234, 0.1911, 0.0408, 0.2531, 0.1979, 0.1891,
        0.2433, 0.1956, 0.2667, 0.134 , 0.1073, 0.2023, 0.1794, 0.0227,
        0.1313, 0.1775, 0.1549, 0.1626, 0.0708, 0.0129, 0.0795, 0.0762,
        0.0117, 0.0061, 0.0257, 0.0089, 0.0262, 0.0108, 0.0138, 0.0187,
        0.023 , 0.0057, 0.0113, 0.0131]])

In [8]:
with open('scaler.pkl', 'rb') as f :
    scal = pickle.load(f)

In [9]:
real_pre=scal.transform(real2)

In [10]:
real_pre

array([[0.0629, 0.1065, 0.1526, 0.1229, 0.1437, 0.119 , 0.0884, 0.0907,
        0.2107, 0.3597, 0.5466, 0.5205, 0.5127, 0.5395, 0.6558, 0.8705,
        0.9786, 0.9335, 0.7917, 0.7383, 0.6908, 0.385 , 0.0671, 0.0502,
        0.2717, 0.2839, 0.2234, 0.1911, 0.0408, 0.2531, 0.1979, 0.1891,
        0.2433, 0.1956, 0.2667, 0.134 , 0.1073, 0.2023, 0.1794, 0.0227,
        0.1313, 0.1775, 0.1549, 0.1626, 0.0708, 0.0129, 0.0795, 0.0762,
        0.0117, 0.0061, 0.0257, 0.0089, 0.0262, 0.0108, 0.0138, 0.0187,
        0.023 , 0.0057, 0.0113, 0.0131]])

In [11]:
with open('model.pkl', 'rb') as f :
    model1 = pickle.load(f)

In [12]:
model1.predict(real_pre)[0]

0